spring:
  application:
    name: resume-analyzer

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/resume_analyzer}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:binomial}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

jwt:
  secret-key: bXlTdXBlclNlY3JldEtleUZvclJlc3VtZUFuYWx5emVyUHJvamVjdDEyMzQ1Njc4OTA=