spring:
  application:
    name: resume-analyzer

  datasource:
    url: jdbc:mysql://localhost:3306/resume_analyzer
    username: root
    password: binomial

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret-key: bXlTdXBlclNlY3JldEtleUZvclJlc3VtZUFuYWx5emVyUHJvamVjdDEyMzQ1Njc4OTA=